articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
 

]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    # comment_set = 
    
class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__'

        # fields => 추가할 필드 이름 목록
        # fields = ('content', )

        # exclude => 제외할 필드 이름 목록
        exclude = ('article', )

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    form = CommentForm()

    # comment 목록 조회
    # 첫번째 방법
    # comments = Comment.objects.filter(article=article)

    # 두번째 방법
    # comments = article.comment_set.all()
    #=> views에서 실행하고 변수에 결과를 담아서 html코드에서 실행

    # 세번째방법
    # html 코드에서 article.comment_set.all 사용
    #=> 애초에 html코드에서 실행 

    context = {
        'article': article,
        'form': form,
        # 'comments': comments,

    }

    return render(request, 'detail.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', id=article.id)
    else:
        form = ArticleForm()
        
    context = {
        'form': form,
    }

    return render(request, 'form.html', context)

def comment_create(request, article_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        # form을 저장 => 추가로 넣어야 하는 데이터를 넣기 위해서 저장 멈춰!.!
        comment = form.save(commit=False)

        # # 첫번째 방법(객체를 저장하는 방법)
        # # article_id를 기준으로 article object 가져오기
        # article = Article.objects.get(id=article_id)
        # # article 컬럼에 추가
        # comment.article = article
        # comment.save()

        # 두번째 방법(integer를 저장하는 방법)
        comment.article_id = article_id
        comment.save()

        return redirect('articles:detail', id=article_id)

def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)
    comment.delete()    

    return redirect('articles:detail', id=article_id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{article.title}}</h1>
    <p>{{article.content}}</p>

    <hr>

    <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
        {% csrf_token %}
        {{form}}

        <input type="submit">
    </form>

     <hr>

    {% for comment in article.comment_set.all %}
        <p>
            {{comment.content}}
            <a href="{% url 'articles:comment_delete' article_id=article.id id=comment.id %}">delete</a>
        </p>
    {% endfor %}
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token%}
        {{ form }}
        <input type="submit">
    </form>
{% endblock%}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>
        <hr>
    {% endfor %}
{%  endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">home</a>
    <a href="{% url 'articles:create' %}">create</a>
    {% block body %}
    {% endblock %}
</body>
</html>